// Code generated by fizzbee-mbt generator; DO NOT EDIT.

package counter

import (
	"log"
	"os"
	"testing"

	mbt "github.com/fizzbee-io/fizzbee/mbt/lib/go"
)

// Registry keyed by role type ("" means top-level model actions)
var actionRegistry = map[string]map[string]mbt.ActionFunc{
	"": {},
	"Counter": {
		"Inc": func(inst any, args []mbt.Arg) (any, error) {
			return inst.(CounterRole).ActionInc(args)
		},
		"Get": func(inst any, args []mbt.Arg) (any, error) {
			return inst.(CounterRole).ActionGet(args)
		},
		"Dec": func(inst any, args []mbt.Arg) (any, error) {
			return inst.(CounterRole).ActionDec(args)
		},
	},
}

func TestCounter(t *testing.T) {
	model := NewCounterModel()
	options := GetTestOptions()
	err := mbt.RunTests(t, model, actionRegistry, options)
	if err != nil {
		log.Fatal(err)
	}
}

func TestMain(m *testing.M) {
	mbt.ParseFlags()
	exitCode := m.Run()
	os.Exit(exitCode)
}
