// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../counter.fizz

package counter

import (
	mbt "github.com/fizzbee-io/fizzbee/mbt/lib/go"
)

// Role interfaces

type CounterRole interface {
	mbt.Role
	ActionInc(args []mbt.Arg) (any, error)
	ActionGet(args []mbt.Arg) (any, error)
	ActionDec(args []mbt.Arg) (any, error)
}

// Model interface for the whole specification
type CounterModel interface {
	mbt.Model
}
